map $http_origin $cors_origin {
    default "";
    "~^https?://localhost(:\d+)?$" $http_origin;
    "~^https?://127\.0\.0\.1(:\d+)?$" $http_origin;
    "~^http?://localhost(:\d+)?$" $http_origin;
    "~^http?://127\.0\.0\.1(:\d+)?$" $http_origin;
}
