[package]
name = "opsense-repl"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }

[lints.rust]
warnings = "deny"

[dependencies]
anyhow = { workspace = true }
arrow = { workspace = true }
base64 = "0.22"
chrono = { workspace = true }
comfy-table = { workspace = true }
opsense-core = { path = "../opsense-core", features = ["arrow"] }
opsense-session = { path = "../opsense-session" }
reedline = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
