[package]
name = "opsense-macros"
version.workspace = true
edition = "2024"
rust-version = "1.85"
license.workspace = true

[features]
default = []

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = { version = "1.0", default-features = false }
syn = { version = "3.0.6", default-features = false, features = ["derive", "extra-traits", "full", "parsing", "printing", "proc-macro", "visit", "visit-mut"] }
inventory = "0.3"
rhai = { workspace = true }
