[package]
name = "opsense-qlib"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = []
json = ["dep:serde_json", "dep:serde", "dep:typetag", "opsense-mlib/json", "serde/rc"]
graph = ["dep:tract-onnx", "dep:prost"]

[dependencies]
opsense-mlib = { path = "../opsense-mlib" }
itertools = "0.14"
tracing = { workspace = true }
reqwest = { workspace = true }

# ONNX genotype compilation
tract-onnx = { workspace = true, optional = true }
prost = { workspace = true, optional = true}

# Runtime / serialization
tokio = { workspace = true }
async-trait = { workspace = true }
typetag = { workspace = true, optional = true }
rand = { workspace = true }
csv = "1.3"
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[lints.rust]
warnings = "deny"
