-- Bảng sys_*: chỉ 4 bảng phục vụ admin entity (tenant + token management).
-- Mọi query của Admin đều đi qua 4 bảng này (xem docs/architecture.md §10).

CREATE TABLE IF NOT EXISTS sys_tenant (
  host VARCHAR(200) PRIMARY KEY,
  id BIGINT NOT NULL,
  jwt_mode VARCHAR(20) DEFAULT NULL,
  jwt_secret BIGINT DEFAULT NULL,
  oidc_jwks_url VARCHAR(500) DEFAULT NULL,
  oidc_issuer VARCHAR(255) DEFAULT NULL,
  oidc_client_id VARCHAR(255) DEFAULT NULL,
  oidc_client_secret BIGINT DEFAULT NULL,
  oidc_expected_alg VARCHAR(10) DEFAULT NULL,
  session_secret BIGINT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_oidc (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  jwt_mode VARCHAR(20) DEFAULT NULL,
  jwt_secret BIGINT DEFAULT NULL,
  oidc_jwks_url VARCHAR(500) DEFAULT NULL,
  oidc_issuer VARCHAR(255) DEFAULT NULL,
  oidc_client_id VARCHAR(255) DEFAULT NULL,
  oidc_client_secret BIGINT DEFAULT NULL,
  oidc_expected_alg VARCHAR(10) DEFAULT NULL,
  session_secret BIGINT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_token_map (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  service VARCHAR(200) NOT NULL,
  token BYTEA NOT NULL,

  CONSTRAINT uk_sys_token_map_tenant_service UNIQUE (tenant_id, service)
);

CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  token_hash VARCHAR(64) NOT NULL,
  token_id BIGINT NOT NULL,
  expires_at TIMESTAMPTZ DEFAULT NULL,
  revoked_at TIMESTAMPTZ DEFAULT NULL,
  last_used_at TIMESTAMPTZ DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT uk_sys_user_tenant_user UNIQUE (tenant_id, user_id),
  CONSTRAINT uk_sys_user_token_hash UNIQUE (token_hash)
);

-- Auto-update updated_at trigger cho 4 bảng (Postgres không có ON UPDATE)
CREATE OR REPLACE TRIGGER trg_sys_tenant_updated_at BEFORE UPDATE ON sys_tenant
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE OR REPLACE TRIGGER trg_sys_oidc_updated_at BEFORE UPDATE ON sys_oidc
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE OR REPLACE TRIGGER trg_sys_token_map_updated_at BEFORE UPDATE ON sys_token_map
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE OR REPLACE TRIGGER trg_sys_user_updated_at BEFORE UPDATE ON sys_user
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
