-- Short-lived sessions cho REPL access_token — 5 phút TTL.
-- Postgres: partition theo created_at (mỗi giờ 1 partition).
-- Procedure drop_expired_partitions xóa partitions > 7 ngày (gọi hàng ngày).

-- Parent table (không chứa dữ liệu, chỉ là anchor cho partitions)
CREATE TABLE IF NOT EXISTS sys_short_sessions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id   BIGINT NOT NULL,
    user_id     VARCHAR(255) NOT NULL,
    session_id  VARCHAR(64) NOT NULL,
    token_hash  VARCHAR(64) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- Partition mặc định cho data không khớp range nào (fallback)
CREATE TABLE IF NOT EXISTS sys_short_sessions_default
    PARTITION OF sys_short_sessions DEFAULT;

-- Hàm tạo partition cho 1 giờ cụ thể
-- Gọi: SELECT make_short_session_partition('2026-09-03 14:00:00+00'::timestamptz);
--
-- LƯU Ý: phải dọn dữ liệu nằm trong partition mặc định thuộc khoảng giờ này
-- TRƯỚC khi CREATE TABLE PARTITION OF. Postgres từ chối tạo partition khi
-- partition mặc định còn chứa dòng rơi vào range đó:
--     ERROR: updated partition constraint for default partition
--            "sys_short_sessions_default" would be violated by some row
-- Tình huống thật đã gặp: container khởi động lúc 09:xx trong khi partition
-- của giờ 09 chưa tồn tại, một dòng session ghi lúc đó rơi vào partition
-- mặc định; lần khởi động kế tiếp gọi hàm này và **cả container chết** với
-- lỗi trên, làm sập stack. Dọn trước là điều kiện để bootstrap idempotent.
CREATE OR REPLACE FUNCTION make_short_session_partition(partition_ts TIMESTAMPTZ)
RETURNS TEXT AS $$
DECLARE
    partition_name TEXT;
    start_ts       TIMESTAMPTZ;
    end_ts         TIMESTAMPTZ;
    moved_rows     BIGINT := 0;
BEGIN
    start_ts := date_trunc('hour', partition_ts);
    end_ts   := start_ts + INTERVAL '1 hour';
    partition_name := 'sys_short_sessions_' || to_char(start_ts, 'YYYYMMDDHH24MI');

    -- Bước 1: đưa dòng lọt vào partition mặc định ra staging.
    --
    -- KHÔNG thể tạo partition khi partition mặc định còn dòng thuộc range:
    -- Postgres từ chối vì ràng buộc của partition mặc định sẽ bị vi phạm. Và
    -- cũng không thể `INSERT` lại trước khi partition tồn tại (dòng sẽ rơi
    -- ngược về partition mặc định). Nên staging là bước trung gian bắt buộc.
    CREATE TEMP TABLE IF NOT EXISTS _ssp_stage (
        LIKE sys_short_sessions INCLUDING ALL
    ) ON COMMIT DROP;

    EXECUTE format(
        'WITH moved AS (
             DELETE FROM sys_short_sessions_default
             WHERE created_at >= %L AND created_at < %L
             RETURNING id, tenant_id, user_id, session_id, token_hash,
                       expires_at, created_at
         )
         INSERT INTO _ssp_stage
         SELECT * FROM moved',
        start_ts, end_ts
    );
    GET DIAGNOSTICS moved_rows = ROW_COUNT;

    -- Bước 2: giờ partition mặc định đã sạch cho range này ⇒ tạo được.
    -- (Nếu partition đã tồn tại thì IF NOT EXISTS là no-op, vẫn an toàn.)
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF sys_short_sessions
         FOR VALUES FROM (%L) TO (%L)',
        partition_name, start_ts, end_ts
    );

    -- Bước 3: trả dòng về bảng cha; Postgres tự định tuyến vào partition mới.
    IF moved_rows > 0 THEN
        EXECUTE format(
            'INSERT INTO sys_short_sessions
                 (id, tenant_id, user_id, session_id, token_hash, expires_at, created_at)
             SELECT id, tenant_id, user_id, session_id, token_hash, expires_at, created_at
             FROM _ssp_stage
             ORDER BY created_at, id'
        );
        RAISE NOTICE 'Moved % row(s) from default partition into %', moved_rows, partition_name;
    END IF;

    RETURN partition_name;
END;
$$ LANGUAGE plpgsql;

-- Procedure drop partitions > 7 ngày tuổi
-- Gọi: CALL drop_expired_short_session_partitions();
CREATE OR REPLACE PROCEDURE drop_expired_short_session_partitions()
LANGUAGE plpgsql AS $$
DECLARE
    partition_record RECORD;
    cutoff_ts        TIMESTAMPTZ := CURRENT_TIMESTAMP - INTERVAL '7 days';
BEGIN
    FOR partition_record IN
        SELECT
            child.relname       AS partition_name,
            pg_get_expr(child.relpartbound, child.oid, 'PARTITION BOUND')
                                AS bound_spec
        FROM pg_inherits
        JOIN pg_class parent ON pg_inherits.inhparent = parent.oid
        JOIN pg_class child  ON pg_inherits.inhrelid = child.oid
        WHERE parent.relname = 'sys_short_sessions'
          AND child.relname != 'sys_short_sessions_default'
          AND child.relname ~ '^sys_short_sessions_[0-9]+$'
    LOOP
        -- Parse partition range start từ bound_spec, drop nếu cũ
        IF partition_record.bound_spec LIKE '%' || to_char(cutoff_ts, 'YYYY%' ) || '%'
           AND partition_record.partition_name < 'sys_short_sessions_' || to_char(cutoff_ts, 'YYYYMMDDHH24MI')
        THEN
            EXECUTE format('DROP TABLE IF EXISTS %I', partition_record.partition_name);
            RAISE NOTICE 'Dropped old partition: %', partition_record.partition_name;
        END IF;
    END LOOP;
END;
$$;

-- Tự động tạo partition cho giờ hiện tại + 2 giờ tới (tránh lỗi nếu chưa có)
DO $$
BEGIN
    PERFORM make_short_session_partition(CURRENT_TIMESTAMP);
    PERFORM make_short_session_partition(CURRENT_TIMESTAMP + INTERVAL '1 hour');
    PERFORM make_short_session_partition(CURRENT_TIMESTAMP + INTERVAL '2 hours');
END;
$$;

-- Index trên mỗi partition (Postgres tự điều phối xuống partition)
CREATE INDEX IF NOT EXISTS idx_short_sessions_token_hash
    ON sys_short_sessions(token_hash);
CREATE INDEX IF NOT EXISTS idx_short_sessions_expires
    ON sys_short_sessions(expires_at);
