-- OAuth2 Device Authorization Grant (RFC 8628) — device_code table.
-- Lưu tạm device flow state khi console/CLI bắt đầu authenticate.
-- Sau khi user duyệt trên browser (POST /device/verify), access_token được
-- phát hành và device_code chuyển sang status = 'approved' (hoặc xóa sau 10 phút).

CREATE TABLE IF NOT EXISTS sys_device_code (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL,
    device_code     VARCHAR(128) NOT NULL UNIQUE,
    user_code       VARCHAR(16) NOT NULL UNIQUE,
    interval_secs   INT NOT NULL DEFAULT 5,
    expires_at      TIMESTAMPTZ NOT NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'pending',
    -- Sau khi user duyệt:
    user_id         VARCHAR(255) DEFAULT NULL,
    client_id       VARCHAR(255) NOT NULL DEFAULT 'opsense-cli',
    approved_at     TIMESTAMPTZ DEFAULT NULL,
    -- Tokens được phát hành (NULL cho đến khi approve):
    access_token    VARCHAR(512) DEFAULT NULL,
    refresh_token   VARCHAR(512) DEFAULT NULL,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Index cho lookup nhanh theo user_code (user nhập trên browser)
CREATE INDEX IF NOT EXISTS idx_device_code_user_code ON sys_device_code(user_code);

-- Index cho poll: device_code + status + expires_at
CREATE INDEX IF NOT EXISTS idx_device_code_poll
    ON sys_device_code(device_code, status, expires_at);

-- Auto-update updated_at
CREATE OR REPLACE TRIGGER trg_sys_device_code_updated_at
    BEFORE UPDATE ON sys_device_code
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
