-- Long-lived sessions cho MCP client — Ed25519 keypair signing.
-- TTL 8h. Cleanup: lazy (đọc thấy expired thì xóa trước khi trả).

CREATE TABLE IF NOT EXISTS sys_long_sessions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL,
    user_id         VARCHAR(255) NOT NULL,
    session_id      VARCHAR(64) NOT NULL UNIQUE,
    -- private_key_enc = Ed25519 private key (32 bytes), mã hóa AES-256-GCM
    -- bằng MASTER_KEY (sops::encrypt). session_id = base64(public_key).
    private_key_enc BYTEA NOT NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'active',
    expires_at      TIMESTAMPTZ NOT NULL,
    last_used_at    TIMESTAMPTZ DEFAULT NULL,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Index: lookup nhanh theo tenant + user (list sessions)
CREATE INDEX IF NOT EXISTS idx_long_sessions_tenant_user
    ON sys_long_sessions(tenant_id, user_id);

-- Index: cleanup expired sessions
CREATE INDEX IF NOT EXISTS idx_long_sessions_expires
    ON sys_long_sessions(expires_at, status);

-- Auto-update updated_at
CREATE OR REPLACE TRIGGER trg_sys_long_sessions_updated_at
    BEFORE UPDATE ON sys_long_sessions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
