-- Short-lived sessions cho REPL access_token — 5 phút TTL.
-- Postgres: partition theo created_at (mỗi giờ 1 partition).
-- Procedure drop_expired_partitions xóa partitions > 7 ngày (gọi hàng ngày).

-- Parent table (không chứa dữ liệu, chỉ là anchor cho partitions)
CREATE TABLE IF NOT EXISTS sys_short_sessions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id   BIGINT NOT NULL,
    user_id     VARCHAR(255) NOT NULL,
    session_id  VARCHAR(64) NOT NULL,
    token_hash  VARCHAR(64) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- Partition mặc định cho data không khớp range nào (fallback)
CREATE TABLE IF NOT EXISTS sys_short_sessions_default
    PARTITION OF sys_short_sessions DEFAULT;

-- Hàm tạo partition cho 1 giờ cụ thể
-- Gọi: SELECT make_short_session_partition('2026-09-03 14:00:00+00'::timestamptz);
CREATE OR REPLACE FUNCTION make_short_session_partition(partition_ts TIMESTAMPTZ)
RETURNS TEXT AS $$
DECLARE
    partition_name TEXT;
    start_ts       TIMESTAMPTZ;
    end_ts         TIMESTAMPTZ;
BEGIN
    start_ts := date_trunc('hour', partition_ts);
    end_ts   := start_ts + INTERVAL '1 hour';
    partition_name := 'sys_short_sessions_' || to_char(start_ts, 'YYYYMMDDHH24MI');

    -- Tạo partition nếu chưa có
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF sys_short_sessions
         FOR VALUES FROM (%L) TO (%L)',
        partition_name, start_ts, end_ts
    );

    RETURN partition_name;
END;
$$ LANGUAGE plpgsql;

-- Procedure drop partitions > 7 ngày tuổi
-- Gọi: CALL drop_expired_short_session_partitions();
CREATE OR REPLACE PROCEDURE drop_expired_short_session_partitions()
LANGUAGE plpgsql AS $$
DECLARE
    partition_record RECORD;
    cutoff_ts        TIMESTAMPTZ := CURRENT_TIMESTAMP - INTERVAL '7 days';
BEGIN
    FOR partition_record IN
        SELECT
            child.relname       AS partition_name,
            pg_get_expr(child.relpartbound, child.oid, 'PARTITION BOUND')
                                AS bound_spec
        FROM pg_inherits
        JOIN pg_class parent ON pg_inherits.inhparent = parent.oid
        JOIN pg_class child  ON pg_inherits.inhrelid = child.oid
        WHERE parent.relname = 'sys_short_sessions'
          AND child.relname != 'sys_short_sessions_default'
          AND child.relname ~ '^sys_short_sessions_[0-9]+$'
    LOOP
        -- Parse partition range start từ bound_spec, drop nếu cũ
        IF partition_record.bound_spec LIKE '%' || to_char(cutoff_ts, 'YYYY%' ) || '%'
           AND partition_record.partition_name < 'sys_short_sessions_' || to_char(cutoff_ts, 'YYYYMMDDHH24MI')
        THEN
            EXECUTE format('DROP TABLE IF EXISTS %I', partition_record.partition_name);
            RAISE NOTICE 'Dropped old partition: %', partition_record.partition_name;
        END IF;
    END LOOP;
END;
$$;

-- Tự động tạo partition cho giờ hiện tại + 2 giờ tới (tránh lỗi nếu chưa có)
DO $$
BEGIN
    PERFORM make_short_session_partition(CURRENT_TIMESTAMP);
    PERFORM make_short_session_partition(CURRENT_TIMESTAMP + INTERVAL '1 hour');
    PERFORM make_short_session_partition(CURRENT_TIMESTAMP + INTERVAL '2 hours');
END;
$$;

-- Index trên mỗi partition (Postgres tự điều phối xuống partition)
CREATE INDEX IF NOT EXISTS idx_short_sessions_token_hash
    ON sys_short_sessions(token_hash);
CREATE INDEX IF NOT EXISTS idx_short_sessions_expires
    ON sys_short_sessions(expires_at);
