server {
    server_name %%HTTP_SERVER%% %%TOR_SERVER%%;
    listen 8080 reuseport;

    set_by_lua_block $environment {
        return os.getenv("ENVIRONMENT") or "prod"
    }

    if ($is_attack = "1") {
	return 403;
    }

    resolver 1.1.1.1 8.8.8.8 ipv6=off valid=30s;
    resolver_timeout 10s;

    root /var/www/html;
    index index.html index.php;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header X-XSS-Protection "1; mode=block" always;

    if ($request_method !~ ^(GET|POST|PUT|PATCH|HEAD)$) {
        return 405;
    }

    error_page 404 @handle_404;
    proxy_intercept_errors on;

    include http.d/vhost/*.conf;
}
