[package]
name = "opsense"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Centralize site reliability engineer's daily activities"

#[lints.rust]
#warnings = "deny"

[[bin]]
name = "opsense"
path = "src/main.rs"

[dependencies]
dotenvy = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
tonic = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
reqwest = { workspace = true }
reedline = { workspace = true }
comfy-table = { workspace = true }
anyhow = { workspace = true }
rmcp = { workspace = true }
ed25519-dalek = { workspace = true }
rand = { workspace = true }
subtle = { workspace = true }
chrono = { workspace = true }
base64 = { workspace = true }

axum = { workspace = true, features = ["macros", "multipart", "ws"] }
axum-metrics = { workspace = true }
axum-macros = { workspace = true }
axum-extra = { workspace = true }
axum-prometheus = { workspace = true }
async-graphql = { workspace = true }
async-graphql-axum = { workspace = true }
headers = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
sentry = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
tracing-opentelemetry = { workspace = true }

opsense-model = { path = "../opsense-model" }
opsense-core = { path = "../opsense-core" }
opsense-components = { path = "../opsense-components" }
opsense-proto = { path = "../opsense-proto" }
opsense-libs = { path = "../opsense-libs" }
opsense-runner = { path = "../opsense-runner" }
