[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid
user=root

[program:app]
command=/app/opsense serve
directory=/app
autostart=true
autorestart=true
stopsignal=TERM
stopwaitsecs=360
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=root
environment=HOME="/app",GATEWAY_LISTENER="unix",OPSENSE_RUNNER_GRPC="opsense-runner:50051"
priority=1

[program:nginx]
command=/bin/bash /app/nginx.sh
directory=/app
autostart=true
autorestart=true
startsecs=10
stopsignal=INT
stopwaitsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=root
environment=NGINX_DIR="/usr/local/openresty/nginx/conf",USE_TOR="false"
priority=2

[program:alloy]
command=/bin/bash /app/alloy.sh
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=0
